version: '3.8'

services:
  base:
    build:
      context: .
      dockerfile: Dockerfile.base
    image: homelab_base
    container_name: homelab_base_test
    command: /bin/bash

  web:
    build: .
    command: gunicorn homelab.wsgi:application --bind 10.60.1.115:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SECRET_KEY=django-insecure-hc%4=(rovnz6&-&jfemw6y(ss&2o1f8ao-#eh&i+s2s%8s!#tt
      - HOME_ASSISTANT_API_URL=http://home_assistant:8123/api/
      - HOME_ASSISTANT_TOKEN=your_long_lived_access_token
      - DB_NAME=homelab
      - DB_USER=homelab
      - DB_PASS=homelab_secret
      - DB_SERVICE=db
      - DB_SERVICE: postgres
  nginx:
    image: nginx:1.21.6
    ports:
      - "80:80"
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
      - static_volume:/app/static
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume: