version: '3.8'

services:
  db:
    hostname: prostgres
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=homelab
      - POSTGRES_USER=homelab_user
      - POSTGRES_PASSWORD=homelab_password
    ports:
      - "5432:5432"

  web:
    hostname: web
    build:
      context: .
      dockerfile: Dockerfile.web
    image: drrohin/homelab_web:latest
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SECRET_KEY=django-insecure-hc%4=(rovnz6&-&jfemw6y(ss&2o1f8ao-#eh&i+s2s%8s!#tt
      - HOME_ASSISTANT_API_URL=http://home_assistant:8123/api/
      - HOME_ASSISTANT_TOKEN=your_long_lived_access_token
      - DB_NAME=homelab
      - DB_USER=homelab_user
      - DB_PASS=homelab_secret
      - DB_HOST=postgres
    depends_on:
      - db

  home_assistant:
    hostname: home_assistant
    image: homeassistant/home-assistant:stable
    volumes:
      - /PATH_TO_YOUR_CONFIG:/config
    environment:
      - TZ=America/Chicago
    ports:
      - "8123:8123"
    restart: unless-stopped

volumes:
  postgres_data:
  static_volume:

networks:
  homelab_network:
    driver: bridge
    attachable: true