version: '3.8'

services:
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=homelab
      - POSTGRES_USER=homelab_user
      - POSTGRES_PASSWORD=homelab_password
    ports:
      - "5432:5432"

  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    image: drrohin/homelab_web:latest
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SECRET_KEY=django-insecure-hc%4=(rovnz6&-&jfemw6y(ss&2o1f8ao-#eh&i+s2s%8s!#tt
      - HOME_ASSISTANT_API_URL=http://home_assistant:8123/api/
      - HOME_ASSISTANT_TOKEN=your_long_lived_access_token
      - DB_NAME=homelab
      - DB_USER=homelab
      - DB_PASS=homelab_secret
      - DB_SERVICE=postgres
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
    networks:
      - homelab_network

  nginx:
    image: nginx:1.21.6
    ports:
      - "80:80"
    volumes:
      - ./config/nginx/security/file:/etc/nginx/security/file:ro
      - ./config/nginx:/etc/nginx/conf.d
      - static_volume:/app/static
    depends_on:
      - web
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
    networks:
      - homelab_network

volumes:
  postgres_data:
  static_volume:

networks:
  homelab_network:
    driver: overlay
    attachable: true