version: '3.8'

services:
  pihole:
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    environment:
      TZ: ${PIHOLE_TIMEZONE}
      WEBPASSWORD: ${PIHOLE_ADMIN_PASSWORD}
    volumes:
       - ./etc-pihole/:/etc/pihole/
       - ./etc-dnsmasq.d/:/etc/dnsmasq.d/
    restart: unless-stopped