version: '3.8'

services:
  postgres:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: homelab
      POSTGRES_USER: homelab
      POSTGRES_PASSWORD: homelab_secret
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
    ports:
      - "5432:5432"

volumes:
  postgres_data: